export interface Course {
  id: string;
  title: string;
  type: 'course' | 'learning-path';
  instructor: string;
  instructorAvatar: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  topics: string[];
  tools: string[];
  duration: string;
  durationLabel: string;
  lessons: number;
  enrolled: number;
  rating: number;
  isNew: boolean;
  status: 'published' | 'draft';
  thumbnail: string;
  description: string;
  color: string;
  createdAt: string;
}

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Real World Projects on RAG',
    type: 'course',
    instructor: 'Krish Naik',
    instructorAvatar: 'KN',
    level: 'Intermediate',
    topics: ['Graph RAG', 'AI Agents'],
    tools: ['Python', 'LangChain'],
    duration: '1–4 hours',
    durationLabel: '5 Hours',
    lessons: 5,
    enrolled: 2100,
    rating: 4.6,
    isNew: false,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=450&fit=crop&q=80',
    description: 'Build production-ready RAG systems using LangChain and vector databases.',
    color: '#2D1B69',
    createdAt: '2024-01-15',
  },
  {
    id: 'course-2',
    title: 'Generative AI for Beginners',
    type: 'course',
    instructor: 'Andrew Ng',
    instructorAvatar: 'AN',
    level: 'Beginner',
    topics: ['Generative AI', 'Prompt Engineering'],
    tools: ['Python', 'OpenAI'],
    duration: '< 1 hour',
    durationLabel: '1 Hour',
    lessons: 3,
    enrolled: 5000,
    rating: 4.8,
    isNew: true,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&h=450&fit=crop&q=80',
    description: 'A beginner-friendly introduction to Generative AI concepts and applications.',
    color: '#7C3AED',
    createdAt: '2024-02-01',
  },
  {
    id: 'course-3',
    title: 'Advanced LLMOps',
    type: 'course',
    instructor: 'Harrison Chase',
    instructorAvatar: 'HC',
    level: 'Advanced',
    topics: ['LLMOps', 'MLOps'],
    tools: ['Python', 'LangChain', 'Docker'],
    duration: '> 4 hours',
    durationLabel: '8 Hours',
    lessons: 10,
    enrolled: 1200,
    rating: 4.9,
    isNew: true,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=450&fit=crop&q=80',
    description: 'Master LLM deployment, monitoring, and operations at scale.',
    color: '#DC2626',
    createdAt: '2024-02-10',
  },
  {
    id: 'course-4',
    title: 'Introduction to Machine Learning',
    type: 'course',
    instructor: 'Andrej Karpathy',
    instructorAvatar: 'AK',
    level: 'Beginner',
    topics: ['Machine Learning', 'Deep Learning'],
    tools: ['Python', 'Scikit-learn'],
    duration: '> 4 hours',
    durationLabel: '10 Hours',
    lessons: 15,
    enrolled: 8000,
    rating: 4.9,
    isNew: false,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=800&h=450&fit=crop&q=80',
    description: 'Comprehensive introduction to ML algorithms and practical implementations.',
    color: '#D97706',
    createdAt: '2024-01-05',
  },
  {
    id: 'course-5',
    title: 'AI Engineering Mastery',
    type: 'learning-path',
    instructor: 'Multiple Instructors',
    instructorAvatar: 'MI',
    level: 'Advanced',
    topics: ['AI Agents', 'LLMOps', 'Graph RAG'],
    tools: ['Python', 'LangChain', 'Strands'],
    duration: '> 4 hours',
    durationLabel: '40 Hours',
    lessons: 50,
    enrolled: 1500,
    rating: 4.8,
    isNew: true,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=450&fit=crop&q=80',
    description: 'Complete learning path to become a professional AI engineer.',
    color: '#059669',
    createdAt: '2024-03-01',
  },
  {
    id: 'course-6',
    title: 'Data Science Fundamentals',
    type: 'learning-path',
    instructor: 'Multiple Instructors',
    instructorAvatar: 'MI',
    level: 'Beginner',
    topics: ['Data Science', 'Python', 'Machine Learning'],
    tools: ['Python', 'Pandas', 'Matplotlib'],
    duration: '> 4 hours',
    durationLabel: '30 Hours',
    lessons: 35,
    enrolled: 4000,
    rating: 4.7,
    isNew: false,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop&q=80',
    description: 'From Python basics to machine learning — the complete data science journey.',
    color: '#0891B2',
    createdAt: '2024-01-20',
  },
  {
    id: 'course-7',
    title: 'Generative AI Developer',
    type: 'learning-path',
    instructor: 'Multiple Instructors',
    instructorAvatar: 'MI',
    level: 'Intermediate',
    topics: ['Generative AI', 'AI Agents', 'Prompt Engineering'],
    tools: ['Python', 'OpenAI', 'LangChain'],
    duration: '> 4 hours',
    durationLabel: '25 Hours',
    lessons: 28,
    enrolled: 2500,
    rating: 4.9,
    isNew: false,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1686191128892-3b37add4c844?w=800&h=450&fit=crop&q=80',
    description: 'Build real-world generative AI applications from scratch.',
    color: '#EA580C',
    createdAt: '2024-02-15',
  },
  {
    id: 'course-8',
    title: 'Prompt Engineering Specialization',
    type: 'learning-path',
    instructor: 'Multiple Instructors',
    instructorAvatar: 'MI',
    level: 'Intermediate',
    topics: ['Prompt Engineering', 'Generative AI'],
    tools: ['OpenAI', 'Gemini', 'Claude'],
    duration: '1–4 hours',
    durationLabel: '4 Hours',
    lessons: 8,
    enrolled: 3000,
    rating: 4.6,
    isNew: false,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=450&fit=crop&q=80',
    description: 'Master the art of prompting LLMs for production use cases.',
    color: '#7C3AED',
    createdAt: '2024-03-10',
  },
  {
    id: 'course-9',
    title: 'Building AI Agents with LangChain',
    type: 'course',
    instructor: 'Harrison Chase',
    instructorAvatar: 'HC',
    level: 'Intermediate',
    topics: ['AI Agents', 'LangChain'],
    tools: ['Python', 'LangChain'],
    duration: '1–4 hours',
    durationLabel: '3 Hours',
    lessons: 6,
    enrolled: 1800,
    rating: 4.7,
    isNew: false,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=450&fit=crop&q=80',
    description: 'Build autonomous AI agents that can reason, plan, and act.',
    color: '#0EA5E9',
    createdAt: '2024-02-20',
  },
  {
    id: 'course-10',
    title: 'TensorFlow for Deep Learning',
    type: 'course',
    instructor: 'Laurence Moroney',
    instructorAvatar: 'LM',
    level: 'Intermediate',
    topics: ['Deep Learning', 'Machine Learning'],
    tools: ['Python', 'TensorFlow'],
    duration: '> 4 hours',
    durationLabel: '6 Hours',
    lessons: 12,
    enrolled: 6000,
    rating: 4.8,
    isNew: false,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=450&fit=crop&q=80',
    description: 'Master deep learning with TensorFlow and Keras from scratch.',
    color: '#FF6B35',
    createdAt: '2024-01-25',
  },
  {
    id: 'course-11',
    title: 'Getting Started with Gemini',
    type: 'course',
    instructor: 'Google Team',
    instructorAvatar: 'GT',
    level: 'Beginner',
    topics: ['Generative AI', 'Prompt Engineering'],
    tools: ['Gemini', 'Python'],
    duration: '< 1 hour',
    durationLabel: '45 Mins',
    lessons: 2,
    enrolled: 4500,
    rating: 4.9,
    isNew: false,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=450&fit=crop&q=80',
    description: "Get started with Google's Gemini AI model for real-world applications.",
    color: '#4285F4',
    createdAt: '2024-03-05',
  },
  {
    id: 'course-12',
    title: 'Graph RAG in Production',
    type: 'course',
    instructor: 'Krish Naik',
    instructorAvatar: 'KN',
    level: 'Advanced',
    topics: ['Graph RAG', 'LLMOps'],
    tools: ['Python', 'Neo4j', 'LangChain'],
    duration: '1–4 hours',
    durationLabel: '3.5 Hours',
    lessons: 7,
    enrolled: 900,
    rating: 4.5,
    isNew: false,
    status: 'draft',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&h=450&fit=crop&q=80',
    description: 'Deploy knowledge graph-powered RAG systems in production environments.',
    color: '#84CC16',
    createdAt: '2024-03-20',
  },
];
